name: DISABLED (temporarily)

on:
  workflow_dispatch:

jobs:
  disabled:
    if: ${{ false }}
    runs-on: [self-hosted, odoo]
    steps:
      - run: echo "Temporarily disabled while stabilizing odoo-upgrade.yml"
