name: Odoo Module Auto-Upgrade

on:
  workflow_dispatch:
  push:
    paths:
      - "energy_broker_uk/**"
      - ".github/workflows/odoo-upgrade.yml"

jobs:
  upgrade-and-verify:
    runs-on: [self-hosted, odoo]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show runner and Odoo paths
        run: |
          whoami
          ls -l /opt/odoo19/odoo-bin || true
          ls -l /opt/odoo19env/bin/python3 || true
          ls -l /opt/odoo19/odoo19.conf || true

      - name: Stop Odoo
        run: sudo systemctl stop odoo19.service

      - name: Upgrade module (as odoo19 via wrapper)
        run: sudo /usr/local/sbin/odoo-upgrade-energy

      - name: Start Odoo
        run: sudo systemctl start odoo19.service

      - name: Tail Odoo log (last 200)
        run: |
          if [ -f /opt/odoo19/log/logfile.txt ]; then
            tail -n 200 /opt/odoo19/log/logfile.txt
          else
            sudo journalctl -u odoo19.service -n 200 --no-pager || true
          fi

      - name: Verify (no critical errors in last 200 lines)
        run: |
          if [ -f /opt/odoo19/log/logfile.txt ]; then
            tail -n 200 /opt/odoo19/log/logfile.txt | grep -E "CRITICAL|Traceback|ERROR" -n && exit 1 || echo "OK"
          else
            sudo journalctl -u odoo19.service -n 200 --no-pager | grep -E "CRITICAL|Traceback|ERROR" -n && exit 1 || echo "OK"
          fi
