name: Odoo Module Auto-Upgrade

on:
  workflow_dispatch:
  push:
    paths:
      - "energy_broker_uk/**"
      - ".github/workflows/odoo-upgrade.yml"

jobs:
  upgrade:
    runs-on: [self-hosted, odoo]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop Odoo
        run: sudo systemctl stop odoo19.service

      - name: Upgrade module (as odoo19)
        run: |
          sudo -u odoo19 /opt/odoo19env/bin/python3 /opt/odoo19/odoo-bin \
            -c /opt/odoo19/odoo19.conf \
            -d dominicanparadeuk \
            -u energy_broker_uk \
            --stop-after-init

      - name: Start Odoo
        run: sudo systemctl start odoo19.service

      - name: Tail Odoo log (last 200)
        run: tail -n 200 /opt/odoo19/log/logfile.txt

      - name: Verify (no critical errors in last 200 lines)
        run: |
          tail -n 200 /opt/odoo19/log/logfile.txt | grep -E "CRITICAL|Traceback|ERROR" -n && exit 1 || echo "OK"
